version: "3.7"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend

  client:
    container_name: client
    build:
      context: ./cc-verifier-fe
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./cc-verifier-fe:/app 
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
    links:
      - server
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: ./cc-verifier-be
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: pg
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: dev
    volumes:
      - ./cc-verifier-be:/app 
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
    links:
      - pg
    depends_on:
      - pg

  pg:
    container_name: pg
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
